import type {
  HarnessRecommendation,
  HarnessReport,
  ParsedSession,
  RiskHit,
} from "@/lib/types";
import { dismissedRecommendations, effectiveRules, riskHitsForSession } from "./risk-tags";

const RECOMMEND_MIN_OCCURRENCES = 3;

// Roll up harness signals across all sessions of a project. The expensive bit
// (riskHitsForSession + hook scan) is per-parsed-session — the caller already
// has parsed sessions in hand.
export function deriveHarness(parsedSessions: ParsedSession[]): HarnessReport {
  const allHits: RiskHit[] = [];
  for (const p of parsedSessions) allHits.push(...riskHitsForSession(p));

  // riskByTag
  const byTag = new Map<string, { count: number; guarded: number }>();
  for (const h of allHits) {
    const cur = byTag.get(h.tag) ?? { count: 0, guarded: 0 };
    cur.count += 1;
    if (h.guarded) cur.guarded += 1;
    byTag.set(h.tag, cur);
  }
  const riskByTag = [...byTag.entries()]
    .map(([tag, v]) => ({ tag, ...v }))
    .sort((a, b) => b.count - a.count);

  // topRisky: by (tag, toolName, detail)
  const byKey = new Map<
    string,
    { tag: string; toolName: string; detail: string; count: number; guarded: number }
  >();
  for (const h of allHits) {
    const key = `${h.tag}::${h.toolName}::${h.detail}`;
    const cur =
      byKey.get(key) ?? { tag: h.tag, toolName: h.toolName, detail: h.detail, count: 0, guarded: 0 };
    cur.count += 1;
    if (h.guarded) cur.guarded += 1;
    byKey.set(key, cur);
  }
  const topRisky = [...byKey.values()].sort((a, b) => b.count - a.count).slice(0, 20);

  // hookFires
  const hookKey = new Map<string, { hookName: string; hookEvent: string; count: number; contextTokens: number }>();
  for (const p of parsedSessions) {
    for (const e of p.events) {
      if (e.kind !== "hook") continue;
      const k = `${e.hookEvent}::${e.hookName}`;
      const cur = hookKey.get(k) ?? {
        hookName: e.hookName,
        hookEvent: e.hookEvent,
        count: 0,
        contextTokens: 0,
      };
      cur.count += 1;
      if (e.contentKind === "additional_context") cur.contextTokens += e.estTokens;
      hookKey.set(k, cur);
    }
  }
  const hookFires = [...hookKey.values()].sort((a, b) => b.count - a.count);

  // Recommendations: a (tag, tool) appearing ≥N times where unguarded > 0.
  const dismissed = dismissedRecommendations();
  const recAgg = new Map<string, { tag: string; toolName: string; occurrences: number; guarded: number; samples: Set<string> }>();
  for (const h of allHits) {
    const k = `${h.tag}::${h.toolName}`;
    const cur =
      recAgg.get(k) ?? { tag: h.tag, toolName: h.toolName, occurrences: 0, guarded: 0, samples: new Set<string>() };
    cur.occurrences += 1;
    if (h.guarded) cur.guarded += 1;
    if (cur.samples.size < 5) cur.samples.add(h.detail);
    recAgg.set(k, cur);
  }
  const recommendations: HarnessRecommendation[] = [];
  for (const [k, v] of recAgg.entries()) {
    if (v.occurrences < RECOMMEND_MIN_OCCURRENCES) continue;
    if (v.occurrences - v.guarded === 0) continue; // already fully guarded
    if (dismissed.has(k)) continue;
    const patternSrc = patternForTag(v.tag);
    recommendations.push({
      id: k,
      tag: v.tag,
      toolName: v.toolName,
      occurrences: v.occurrences,
      guarded: v.guarded,
      samples: [...v.samples],
      settingsJson: buildSettingsJson(v.toolName, patternSrc, v.tag),
      hookScript: buildHookScript(v.toolName, patternSrc, v.tag),
    });
  }
  recommendations.sort((a, b) => b.occurrences - a.occurrences);

  return { riskByTag, topRisky, hookFires, recommendations };
}

function patternForTag(tag: string): string {
  // First default pattern source for this tag — good enough for a copy-paste starter.
  for (const r of effectiveRules()) {
    if (r.tag === tag && r.patterns.length > 0) {
      return r.patterns[0].source;
    }
  }
  return ".*";
}

function buildSettingsJson(toolName: string, pattern: string, tag: string): string {
  const cfg = {
    hooks: {
      PreToolUse: [
        {
          matcher: toolName,
          hooks: [
            {
              type: "command",
              command: `bash -c 'CMD=$(jq -r ".tool_input | (.command // .file_path // .url // empty)"); if echo "$CMD" | grep -E ${shellSingleQuote(pattern)} >/dev/null; then echo "[cclog/${tag}] blocked: $CMD" >&2; exit 2; fi'`,
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(cfg, null, 2);
}

function buildHookScript(toolName: string, pattern: string, tag: string): string {
  return `#!/usr/bin/env node
// ~/.claude/hooks/block-${tag}.cjs
// Wired by Claude Code as PreToolUse:${toolName}. Auto-generated by cclog —
// review and tighten before trusting in production.
const fs = require("node:fs");
let payload = {};
try { payload = JSON.parse(fs.readFileSync(0, "utf8")); } catch {}
const input = payload.tool_input ?? {};
const target = input.command ?? input.file_path ?? input.url ?? "";
if (/${pattern}/i.test(target)) {
  console.error(\`[${tag}] blocked: \${target}\`);
  process.exit(2); // exit 2 = deny in Claude Code hook protocol
}
process.exit(0);
`;
}

function shellSingleQuote(s: string): string {
  // wrap regex in single quotes for grep -E; escape any single quotes inside
  return "'" + s.replace(/'/g, "'\\''") + "'";
}
